[project]
name = "my-package-neerajlalji"
version = "0.1.2"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Neeraj Lalji", email = "neeraj.lalji@depop.com" }
]
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.5",
]

[build-system]
requires = ["uv_build>=0.9.8,<0.10.0"]
build-backend = "uv_build"

[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit = true
